name:                mixfix
version:             0.1.0.0
github:              "skyb0rg007/mixfix"
license:             BSD3
author:              "Skye Soss"
maintainer:          "skyler.soss+mixfix@gmail.com"
copyright:           "2019 Skye Soss"

extra-source-files:
- README.md

synopsis:            A parser with support for user-defined mixfix operators
category:            Compilers/Interpreters

description:         Please see the README on GitHub at <https://github.com/skyb0rg007/mixfix#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- text
- containers
- bytestring
- lens
- Earley
- recursion-schemes
- prettyprinter
- parser-combinators
# - singletons
- mtl
- reflex
- data-default
- reflex-dom

library:
  source-dirs: src

executables:
  mixfix:
    main:                app/Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mixfix
  website:
    main:                app/Website.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mixfix

tests:
  mixfix-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mixfix
